apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-credentials
  namespace: ci
spec:
  encryptedData:
    password: AgAS++REowzL+YSynKfi4ClJl7P8rJVwcd7RrqtJtCjueNNA9pNWYlbiZvwzXi3zDjdmxZcbx7w/pAAIo+A/rxf4STDqm++HAqJ27IbC021oVTHDIy61uczOCoeLuPgiB9V9KC2yisiy408RPXG1bjP+NSQMLj/gKcKp8oFfaB0On2GurN+vpxmLbXq4wUWL+XLoPtHoKtMMW6C0Yu+wmUjwDqtc2BYczfDCbEX4SXQEAPWmUIffvo7is38vSzc8XdcnyoOoOP9GTL+SeRc4eIv2pbUPLgzRbmqoYmf8jLtKyIvyIFh8oHqzF37TXtQSxWiTsbZeaq7pJGEKV1xdHdDZyupv5s6if+aqXdq7GcZO5nMRSHzRExB8nXBpieS8WUTi6C+F0gThvISxH/dNI+W9Sj8vRZJuTe9zJygKCvdGIqVGm/Wgh5JADHOekDTWz6iHmZJ4++e0FR1kxG6D8TfPdSJWiQ5V55CDm7c+RJen1EGJEyDQv6d0wK7arCfgK+sGlaa1f4wYMTcTzzAYzu1ZtCj+t0+0IbXKCjuXmEn03PZyQiomRANzfZxXRkUBY3t+C6OHplrCe7roZWwsnnif2m+EtZ81yeDO2Dpx2c9+vckRxsZmd1wePIOMpaHhhbRhUmxy9hZk2eNbElMrOvXFSEXMM3HuvRJRoodkOcqz91pcFkHCaMRht9dkQgsy0cR7ss1awwTGZTqFO69PszeDqipqWiAph9h8RRSGYBG3EMpXkVK9wvN7
    username: AgAsCf31PMEqRjCRDjWxG3zDuTFAejq9Acyma+n+otQetN/p2yoM3QUJK07A3bNv36UGulC1t0h2bUEaJgN1tAmMUdSKQmwYfeiBixIjng7jWQhZBI3GMGiUCX2+QPGoxcSjav2M+2y5IJX+MjamsNyUo1sAcZSIP2sLVkluJC10Ezsx3cDKZGxlxpv3nmzn4YDyCNFloRsqqkJsV81/CVw7ihN7TofU/ldZcWrLvqF9m4Ts9QfIt+RsCNj3EnvM5x9IXBOoa1qQj8m9Ew9c9MtU96q8XS+eUh6pt8zSfUu8l6Hq/iq4qAXGnACZjKkv0vk3SBGN0eVTGjAd+J7EMPt3b9Or50xkPl9lbal/4V7350G2mNDP/iDRBPh7oFfl9/VDEUHgVgDC2fWZ+pBQHXpr8LQ3QieFB9BOgxG554VhvjAT9WVPdCoZFGsFiOZqKyjA2XkctB/kuz6Q3vJ8nsnTiGAS7S7VdHFpmmw0h4vTK2Y3ngXYpuY9hWJiFOPdVbpKdURyuIUNuKuY8xYXuXDayZj/5xBDbefSFZZ+rykSyjcfihownzvEiwF0/jUDlwo/KBPBSYtMC4IC50sUYFTtK7wC8fIcBuL5UTT+HnfiJwfnugebZ/KK8+6l8+mFIdhTBjEfLV3R3NT87P6+YgzoJ/ugs37IU3IvF/1BBokHSiYlu0rUSzWEKBxijYASuyWeqsTxKwmy
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
      namespace: ci
    type: kubernetes.io/basic-auth

