apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  labels:
    app: cnkt-event-listener
  name: cnkt-event-listener
spec:
  serviceAccountName: pipeline
  triggers:
  - name: mq-infra-dev
    interceptors:
      - ref:
          name: "cel"
        params:
        - name: "filter"
          value: "header.match('X-GitHub-Event', 'push') && body.ref == 'refs/heads/qm1-bcbs-demo' && body.repository.full_name == 'bcbs-demo/mq-infra'"
    bindings:
      - ref: cnkt-trigger-binding
    template:
      ref: mq-infra-dev
   - name: mq-spring-app-dev
     interceptors:
       - ref:
           name: "cel"
         params:
         - name: "filter"
           value: "header.match('X-GitHub-Event', 'push') && body.ref == 'refs/heads/mq-spring-bcbs-demo' && body.repository.full_name == 'bcbs-demo/mq-spring-app'"
     bindings:
       - ref: cnkt-trigger-binding
     template:
       ref: mq-spring-app-dev
