apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ci-mq-client-cert
spec:
  dnsNames:
    - >- 
      *.itzroks-550004ysw8-0jjcf0-4b4a324f027aea19c5cbc0c3275c4656-0000.us-east.containers.appdomain.cloud
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - client auth
  keystores:
    jks:
      create: true
      passwordSecretRef:
        key: KEY_STORE_PASSWORD
        name: mq-client-jks-password
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-mq-cluster-issuer
  secretName: mq-client-jks
  subject:
    organizations:
    - ibm
